version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: PleaseWork
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
