// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230430222101_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
            .HasAnnotation("ProductVersion", "7.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ArtProduct", b =>
                {
                    b.Property<Guid>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtDimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ArtPrice")
                        .HasColumnType("real");

                    b.Property<int>("ArtScore")
                        .HasColumnType("int");

                    b.Property<byte[]>("imgBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("ArtId");

                    b.ToTable("ArtProducts");

                    b.HasData(
                        new
                        {
                            ArtId = new Guid("a9fe3cc9-e116-4fa3-be8b-1f1fd327a1db"),
                            ArtDesc = "Birth of Venus is a renaissance style painting by Botticelli. It was painted in 1485. ",
                            ArtDimensions = "172.5 x 278.5 cm",
                            ArtName = "Birth of Venus",
                            ArtPrice = 4000f,
                            ArtScore = 35,
                            imgBytes = new byte[0],
                            isAvailable = true
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd2d11e8-eca5-4965-8997-dff0ea2f1bc4"),
                            Email = "john_test@gmail.com",
                            FirstName = "John",
                            IsAdmin = true,
                            LastName = "Doe",
                            Phone = "612-666-1234",
                            Password = "password",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = new Guid("fb172853-b5b6-4b51-a5c8-5405fd898d92"),
                            Email = "jane_test@gmail.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            LastName = "Deer",
                            Phone = "612-666-1234",
                            Password = "test",
                            Username = "janedeer"
                        });
                });
        }
    }
}
