// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230307181028_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ArtProduct", b =>
                {
                    b.Property<int>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtId"));

                    b.Property<string>("ArtDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtDimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ArtPrice")
                        .HasColumnType("real");

                    b.Property<int>("ArtScore")
                        .HasColumnType("int");

                    b.Property<byte[]>("imgBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("ArtId");

                    b.ToTable("ArtProducts");

                    b.HasData(
                        new
                        {
                            ArtId = 1,
                            ArtDesc = "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs.",
                            ArtDimensions = "7*12",
                            ArtName = "Harry Potter and the Sorcerer's Stone",
                            ArtPrice = 2000f,
                            ArtScore = 15,
                            imgBytes = new byte[0],
                            isAvailable = true
                        },
                        new
                        {
                            ArtId = 2,
                            ArtDesc = "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. ",
                            ArtDimensions = "7*12",
                            ArtName = "Harry Potter and the Chamber of Secrets",
                            ArtPrice = 3000f,
                            ArtScore = 20,
                            imgBytes = new byte[0],
                            isAvailable = false
                        },
                        new
                        {
                            ArtId = 3,
                            ArtDesc = "Walter Isaacson’s “enthralling” (The New Yorker) worldwide bestselling biography of Apple cofounder Steve Jobs.",
                            ArtDimensions = "12*18",
                            ArtName = "Steve Jobs",
                            ArtPrice = 4000f,
                            ArtScore = 35,
                            imgBytes = new byte[0],
                            isAvailable = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
